<a href="https://colab.research.google.com/github/vcbonani/Python/blob/main/Projeto_desafio_1_vendas_online.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

O objetivo desse projeto é realizar uma análise dos resultados de um evento com os clientes de uma empresa de vendas online. Foi coletado um conjunto de dados que contém os clientes que mais gastaram com produtos dentro de 5 dias de vendas, que é o período de duração do evento. Essa análise vai identificar o cliente com a maior compra na semana, que irá receber um prêmio da loja, e posteriormente, ela pode ajudar a empresa a criar novas estratégias para atrair mais clientes.

A base de dados utilizada nessa análise é a dados_vendas_clientes.json e contém informações importantes sobre os clientes como, o nome de cadastro do cliente, o valor total pago na compra e o dia da compra.

Sabendo essas informações, o desafio do projeto 1: vendas online será abrir a base de dados com Pandas e aplicar o json_normalize.

In [ ]:
import pandas as pd

In [ ]:
dados = pd.read_json('/content/dados_vendas_clientes.json')
dados = pd.json_normalize(dados['dados_vendas'])
dados

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

## Desafio: trabalhando em outros contextos

Etapa 2

Projeto desafio 1: vendas online

Lemos a base de dados no desafio anterior, agora podemos avançar nas transformações desses dados. Então, o novo desafio do projeto 1 será dividido em algumas metas:

* Remover os dados em listas dentro do DataFrame;
* Verificar os tipos de dados;
* Identificar colunas numéricas;
* Transformar a coluna numérica para o tipo numérico.

In [ ]:
# Remover os dados em listas dentro do DataFrame

#colunas para remover os dados em listas
colunas = ['Cliente', 'Valor da compra']

#remover os dados em listas e expandindo em registros
dados = dados.explode(colunas).reset_index(drop = True)

dados

   Data de venda             Cliente Valor da compra
0     06/06/2022     @ANA _LUCIA 321        R$ 836,5
1     06/06/2022  DieGO ARMANDIU 210       R$ 573,33
2     06/06/2022  DieGO ARMANDIU 210        R$ 392,8
3     06/06/2022  DieGO ARMANDIU 210       R$ 512,34
4     07/06/2022  Isabely JOanes 738       R$ 825,31
5     07/06/2022  Isabely JOanes 738       R$ 168,07
6     07/06/2022  Isabely JOanes 738       R$ 339,18
7     07/06/2022  Isabely JOanes 738       R$ 314,69
8     08/06/2022  Isabely JOanes 738       R$ 682,05
9     08/06/2022    JOãO Gabriel 671       R$ 386,34
10    08/06/2022  Julya meireles 914       R$ 622,65
11    08/06/2022  Julya meireles 914       R$ 630,79
12    09/06/2022  Julya meireles 914        R$ 390,3
13    09/06/2022     MaRIA Julia 444       R$ 759,16
14    09/06/2022     MaRIA Julia 444       R$ 334,47
15    09/06/2022     MaRIA Julia 444       R$ 678,78
16    10/06/2022     MaRIA Julia 444       R$ 314,24
17    10/06/2022     PEDRO PASCO 812       R$ 311,15
18    10/06/2022    Paulo castro 481       R$ 899,16
19    10/06/2022   Thiago fritzz 883       R$ 885,24

In [ ]:
# Verificar os tipos de dados

dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     object
dtypes: object(3)
memory usage: 612.0+ bytes

In [ ]:
#Identificar colunas numéricas

#verificando quais caracteres precisam ser tratados na coluna valor da compra
dados['Valor da compra'].unique()

array(['R$ 836,5', 'R$ 573,33', 'R$ 392,8', 'R$ 512,34', 'R$ 825,31',
       'R$ 168,07', 'R$ 339,18', 'R$ 314,69', 'R$ 682,05', 'R$ 386,34',
       'R$ 622,65', 'R$ 630,79', 'R$ 390,3', 'R$ 759,16', 'R$ 334,47',
       'R$ 678,78', 'R$ 314,24', 'R$ 311,15', 'R$ 899,16', 'R$ 885,24'],
      dtype=object)

In [ ]:
#importando numpy para auxiliar na conversão do tipo da coluna
import numpy as np

#substituindo R$ e , nos dados da coluna valor da compra
dados['Valor da compra'] = dados['Valor da compra'].apply(lambda elemento: elemento.replace('R$', '').replace(',','.').strip())

#convertendo o tipo da coluna para float
dados['Valor da compra'] = dados['Valor da compra'].astype(np.float64)

#checando os tipos dos dados novamente
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: float64(1), object(2)
memory usage: 612.0+ bytes

## Projeto desafio 1: vendas online
Na etapa 2, trabalhamos na transformação dos dados numéricos. Agora, podemos trabalhar com valores textuais.

Devido a uma instabilidade no site da empresa, tivemos problemas com os nomes dos clientes durante o salvamento. Isso resultou em uma coluna de nomes de clientes com uma mistura de letras, maiúsculas e minúsculas, números e outros caracteres.

Sabendo disso, manipule os textos presentes na coluna Cliente para que seja obtido como resultado os nomes dos clientes em letras minúsculas, com a ausência de caracteres especiais ou números.

In [ ]:
dados

   Data de venda             Cliente  Valor da compra
0     06/06/2022     @ANA _LUCIA 321           836.50
1     06/06/2022  DieGO ARMANDIU 210           573.33
2     06/06/2022  DieGO ARMANDIU 210           392.80
3     06/06/2022  DieGO ARMANDIU 210           512.34
4     07/06/2022  Isabely JOanes 738           825.31
5     07/06/2022  Isabely JOanes 738           168.07
6     07/06/2022  Isabely JOanes 738           339.18
7     07/06/2022  Isabely JOanes 738           314.69
8     08/06/2022  Isabely JOanes 738           682.05
9     08/06/2022    JOãO Gabriel 671           386.34
10    08/06/2022  Julya meireles 914           622.65
11    08/06/2022  Julya meireles 914           630.79
12    09/06/2022  Julya meireles 914           390.30
13    09/06/2022     MaRIA Julia 444           759.16
14    09/06/2022     MaRIA Julia 444           334.47
15    09/06/2022     MaRIA Julia 444           678.78
16    10/06/2022     MaRIA Julia 444           314.24
17    10/06/2022     PEDRO PASCO 812           311.15
18    10/06/2022    Paulo castro 481           899.16
19    10/06/2022   Thiago fritzz 883           885.24

In [ ]:
#colocando as letras em minúsculo
dados['Cliente'] = dados['Cliente'].str.lower()

#removendo @ 0 1 2 3 4 5 6 7 8 9 _
dados['Cliente'] = dados['Cliente'].str.replace('[\@\0-9\_]', ' ', regex = True)

<>:5: SyntaxWarning: invalid escape sequence '\@'
<>:5: SyntaxWarning: invalid escape sequence '\@'
/tmp/ipykernel_691/3900994014.py:5: SyntaxWarning: invalid escape sequence '\@'
  dados['Cliente'] = dados['Cliente'].str.replace('[\@\0-9\_]', ' ', regex = True)

In [ ]:
dados['Cliente']

0         ana  lucia
1     diego armandiu
2     diego armandiu
3     diego armandiu
4     isabely joanes
5     isabely joanes
6     isabely joanes
7     isabely joanes
8     isabely joanes
9       joão gabriel
10    julya meireles
11    julya meireles
12    julya meireles
13       maria julia
14       maria julia
15       maria julia
16       maria julia
17       pedro pasco
18      paulo castro
19     thiago fritzz
Name: Cliente, dtype: object

Nas etapas anteriores, já trabalhamos com vários tipos de dados, agora podemos trabalhar com os dados de tempo.

Na coluna Data de venda, temos datas em formato 'dia/mês/ano' (dd/mm/AAAA). Transforme esses dados para o tipo datetime e busque uma forma de visualização de subconjunto que possa contribuir no objetivo do contexto que os dados estão inseridos.

Se você não lembra o problema do projeto desafio 1, vou deixar abaixo o texto da situação para facilitar o encontro da informação:

O objetivo desse projeto é realizar uma análise dos resultados de um evento com os clientes de uma empresa de vendas online. Foi coletado um conjunto de dados que contém os clientes que mais gastaram com produtos dentro de 5 dias de vendas, que é o período de duração do evento. Essa análise vai identificar o cliente com a maior compra na semana, que irá receber um prêmio da loja, e posteriormente, ela pode ajudar a empresa a criar novas estratégias para atrair mais clientes.

In [ ]:
#convertendo a coluna data de venda para datetime
dados['Data de venda'] = pd.to_datetime(dados['Data de venda'], format = '%d/%m/%Y')

#conferindo o tipo das colunas
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     datetime64[ns]
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 612.0+ bytes

In [ ]:
dados

   Data de venda             Cliente  Valor da compra
0     2022-06-06      ana  lucia               836.50
1     2022-06-06  diego armandiu               573.33
2     2022-06-06  diego armandiu               392.80
3     2022-06-06  diego armandiu               512.34
4     2022-06-07  isabely joanes               825.31
5     2022-06-07  isabely joanes               168.07
6     2022-06-07  isabely joanes               339.18
7     2022-06-07  isabely joanes               314.69
8     2022-06-08  isabely joanes               682.05
9     2022-06-08    joão gabriel               386.34
10    2022-06-08  julya meireles               622.65
11    2022-06-08  julya meireles               630.79
12    2022-06-09  julya meireles               390.30
13    2022-06-09     maria julia               759.16
14    2022-06-09     maria julia               334.47
15    2022-06-09     maria julia               678.78
16    2022-06-10     maria julia               314.24
17    2022-06-10     pedro pasco               311.15
18    2022-06-10    paulo castro               899.16
19    2022-06-10   thiago fritzz               885.24

In [ ]:
#somando as compras dos clientes ao longo dos dias e ordenando o total de forma descendente
dados.groupby(dados['Cliente'])['Valor da compra'].sum().sort_values(ascending = False)

Cliente
isabely joanes        2329.30
maria julia           2086.65
julya meireles        1643.74
diego armandiu        1478.47
paulo castro           899.16
thiago fritzz          885.24
 ana  lucia            836.50
joão gabriel           386.34
pedro pasco            311.15
Name: Valor da compra, dtype: float64